### ISSUE TITLE
On-disk persistence

### ISSUE THREAD

**Issue by CMCDragonkai** [fmerg/pymerkle#5]
Is there a way to make this pymerkle on-disk durable? Keybase's implementation of a merkle tree exposes an key-value interface where you can plug in a durable key-value datastore. https://github.com/keybase/node-merkle-tree

**Comment by FoteinosMerg** [comment]
Do you mean something more than "saving" the tree into a file and being able to retrieve it from that file? This is currently possible using the `.export()` method and the `.loadFromFile()` static method, see [API](https://github.com/FoteinosMerg/pymerkle/blob/master/API.md).

**Comment by FoteinosMerg** [comment]
Well, no key-value interface is currently provided. But yes, it would be possible to implement one. Nodes of the tree could be easily accessed by some kind of  traversal and thus be assigned a key (if I correctly understand what you mean).

The thing is that storing all nodes seems unnecessary in the first place. In order to reconstruct the tree from some kind of non-volatile memory, one needs only know the hash-digests stored by its leaves (this is due to the topology of the current implementation). This info (along with the prerequisite fixed configs) may be retrieved pretty fast from a `.json` file like the one contained in `tests/exports` using `.loadFromFile()` . For a tree with 3,783,429 nodes (or 1,891,715 leaves) one needs a file of ~138M and ~3.5 minutes to reload.

Let me know if these numbers are satisfactory, or if a key-value storage of nodes would be nevertheless needed for some other reason.

**Comment by fmerg** [comment]
@wfamy these utilities have been removed as they did not properly implement persistence. They were non-optimized convenience methods for dumping the tree to a JSON file and loading it from there. Even if they were stable, they did not scale well for big trees and did not solve the problem of having to load the whole tree to memory. A proper implementation of persistence should provide pluggable storage backends and keep the core of the library unopinionated with respect them.

If you found these functions useful, you can easily implement them using the current API. Just dump the tree metadata and leaf hashes in order; this is enough for recovering the tree  in memory using the `.init_from_entries` static method. Hope this helps.

**Comment by fmerg** [comment]
Persistence handled in version 5.0.0. Use `SqliteTree` as an immediate solution.

**Comment by CMCDragonkai** [comment]
Sorry what's `SqliteTree`? Is that a package/library?

**Comment by fmerg** [comment]
It is one of the implementations provided by pymerkle v5.0.0:

```python
from pymerkle import SqliteTree

tree = SqliteTree('merkle.db')
```
See [here](https://pymerkle.readthedocs.io/en/latest/implementations.html#sqlite) for details.
